export const categoryOptions = [
    {text: 'Men', value: 'men'},
    {text: 'Women', value: 'women'},
    {text: 'Ring', value: 'ring'},
    {text: 'Gloves', value: 'gloves'},
    {text: 'Sunglasses', value: 'sunglasses'},
    {text: 'Hair Band', value: 'hairband'},
    {text: 'Watch', value: 'watch'},
    {text: 'Tie', value: 'tie'},
    {text: 'Earring', value: 'earring'},
    {text: 'hat', value: 'hat'},
    {text: 'Ski suits', value: 'skisuits'},
    {text: 'Mouthguards', value: 'mouthgurads'},
    {text: 'Shin pads', value: 'shinpads'},
    {text: 'Book2', value: 'Book2'},
    {text: 'T-shirt', value: 'tshirt'},
    {text: 'Shirt', value: 'shirt'},
    {text: 'Pants', value: 'pants'},
    {text: 'Hoodie', value: 'hoodie'},
    {text: 'Vitamine C', value: 'vitaminC'},
    {text: 'Baby Powder', value: 'bpowder'},
    {text: 'Syringes', value: 'syringes'},
    {text: 'Bed', value: 'bed'},
    {text: 'Plant', value: 'plant'},
    {text: 'Sofa', value: 'sofa'},
    {text: 'Picture', value: 'picture'},


]